namespace PropertyPilot.Services.CaretakerPortalServices.Models.Properties;

public class InvoicesTabListing
{
    public required Guid InvoiceId { get; set; }
    public required string TenantName { get; set; }
    public string SubUnitName { get; set; } = "";
    public required DateTime IssuedDate { get; set; }
    public required bool IsAutoGenerated { get; set; }
    public required string InvoiceStatus { get; set; }
    public required double Amount { get; set; }
}
